### ISSUE TITLE
支持CentOS吗

### ISSUE THREAD

**Issue by thewon86** [isnowfy/python-vim-instant-markdown#10]
我在CentOS下使用vundle安装插件后，vim打开md文件，输入命令:Instantmd命令后没有任何反应，打开浏览器http://localhost:7000/没有任何东西出来，请问怎么办呢？

**Comment by isnowfy** [comment]
应该是支持的，你看看是不是vim不支持python呢，检查下vim --version | grep +python

**Comment by thewon86** [comment]
这个是支持python的，我检查过。

**Comment by isnowfy** [comment]
装一下pip，然后装一下pip install markdown and pip install pygments试试呢
